name: Run Pytest

on:
 pull_request:
   branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/
      
      - name: Failure log
        if: failure()
        run: echo "直前のステップでエラーが発生しました。"
      
      - name: Print ENV
        run: |
          echo "PYTHONPATH=$PYTHONPATH"
          echo "PATH=$PATH"
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_SHA=$GITHUB_SHA"
          echo "GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME"
          echo "GITHUB_ACTOR=$GITHUB_ACTOR"
          echo "TEST1_API_KEY=${{ secrets.TEST1_API_KEY }}"
      - name: Get Time
        id: get_time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT
        